Vagrant.configure("2") do |config|
  
  config.vm.define "hub" do |hub|
    hub.vm.box = "ubuntu/focal64"
  
    hub.vm.hostname = "hub"
    hub.vm.network "private_network", ip: "192.168.56.2"

    hub.vm.network "forwarded_port", guest: 80, host: 8080     # WebUI
    hub.vm.network "forwarded_port", guest: 8084, host: 50750  # Linkerd Viz Dashboard
    hub.vm.network "forwarded_port", guest: 8081, host: 8081   # CockroachDB Dashboard
    hub.vm.network "forwarded_port", guest: 8222, host: 8222   # NATS Dashboard
    hub.vm.network "forwarded_port", guest: 9000, host: 9000   # QuestDB Dashboard
    hub.vm.network "forwarded_port", guest: 9090, host: 9090   # Prometheus Dashboard
    
    hub.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end

    # Installing Microk8s
    hub.vm.provision "file", source: "./microk8s-tfs-install.sh", destination: "./microk8s-tfs-install.sh"
    hub.vm.provision "shell", inline: "chmod +x ./microk8s-tfs-install.sh && ./microk8s-tfs-install.sh vagrant"

    # Setup Linkerd Viz reverse proxy
    hub.vm.provision "file", source: "../deploy-tfs/reverse-proxy-linkerdviz.sh", destination: "./reverse-proxy-linkerdviz.sh"
    hub.vm.provision "shell", inline: "chmod +x ./reverse-proxy-linkerdviz.sh && ./reverse-proxy-linkerdviz.sh"
  end

  config.vm.define "spoke1" do |spoke1|
    spoke1.vm.box = "ubuntu/focal64"

    spoke1.vm.hostname = "spoke1"
    spoke1.vm.network "private_network", ip: "192.168.56.3"

    spoke1.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end

    # Installing Microk8s
    spoke1.vm.provision "file", source: "./microk8s-tfs-install.sh", destination: "./microk8s-tfs-install.sh"
    spoke1.vm.provision "shell", inline: "chmod +x ./microk8s-tfs-install.sh && ./microk8s-tfs-install.sh vagrant"
  end

  config.vm.define "spoke2" do |spoke2|
    spoke2.vm.box = "ubuntu/focal64"

    spoke2.vm.hostname = "spoke2"
    spoke2.vm.network "private_network", ip: "192.168.56.4"

    spoke2.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end

    # Installing Microk8s
    spoke2.vm.provision "file", source: "./microk8s-tfs-install.sh", destination: "./microk8s-tfs-install.sh"
    spoke2.vm.provision "shell", inline: "chmod +x ./microk8s-tfs-install.sh && ./microk8s-tfs-install.sh vagrant"
  end

end
