$microk8sTfsInstall = <<-'SCRIPT'
sudo dpkg --configure -a
sudo apt-get update -y
sudo apt --fix-broken install -y
sudo apt-get dist-upgrade -y
sudo apt-get install -y ca-certificates curl gnupg lsb-release snapd jq
sudo apt-get install -y docker.io docker-buildx
if [ -s /etc/docker/daemon.json ]; then sudo cat /etc/docker/daemon.json; else echo '{}'; fi \
    | jq 'if has("insecure-registries") then . else .+ {"insecure-registries": []} end' -- \
    | jq '."insecure-registries" |= (.+ ["localhost:32000"] | unique)' -- \
    | tee tmp.daemon.json
sudo mv tmp.daemon.json /etc/docker/daemon.json
sudo chown root:root /etc/docker/daemon.json
sudo chmod 600 /etc/docker/daemon.json
sudo systemctl restart docker
echo '192.168.56.2 controller' | sudo tee -a /etc/hosts
echo '192.168.56.3 spoke1' | sudo tee -a /etc/hosts
sudo snap install microk8s --classic --channel=1.24/stable
sudo snap alias microk8s.kubectl kubectl
sudo usermod -aG microk8s vagrant
sudo usermod -aG docker vagrant
sudo mkdir -p /home/vagrant/.kube
sudo microk8s config > /home/vagrant/.kube/config
sudo chown -f -R vagrant:vagrant /home/vagrant/.kube
if [ "controller" == $(cat /etc/hostname) ]; then
    mkdir /home/vagrant/tfs-ctrl
    git clone https://labs.etsi.org/rep/tfs/controller.git /home/vagrant/tfs-ctrl
    chown -f -R vagrant:vagrant /home/vagrant/tfs-ctrl
fi
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.define "controller" do |controller|
    controller.vm.box = "ubuntu/focal64"
    controller.vm.network "forwarded_port", guest: 80, host: 8080     # WebUI
    controller.vm.network "forwarded_port", guest: 8084, host: 50750  # Linkerd Viz Dashboard
    controller.vm.network "forwarded_port", guest: 8081, host: 8081   # CockroachDB Dashboard
    controller.vm.network "forwarded_port", guest: 8222, host: 8222   # NATS Dashboard
    controller.vm.network "forwarded_port", guest: 9000, host: 9000   # QuestDB Dashboard
    controller.vm.network "forwarded_port", guest: 9090, host: 9090   # Prometheus Dashboard

    controller.vm.hostname = "controller"
    controller.vm.network "private_network", ip: "192.168.56.2"

    controller.vm.provider "virtualbox" do |v|
      v.memory = 6144
      v.cpus = 2
    end

    # Add route for ContainerLab running at the host
    controller.vm.provision "shell", inline: "ip route add 172.100.100.0/24 via 192.168.56.1"

    # Installing Microk8s
    controller.vm.provision "shell", inline: $microk8sTfsInstall

    controller.vm.provision "shell", inline: "echo Rebooting...", reboot: true
  end

  config.vm.define "spoke1" do |spoke1|
    spoke1.vm.box = "ubuntu/focal64"

    spoke1.vm.hostname = "spoke1"
    spoke1.vm.network "private_network", ip: "192.168.56.3"

    spoke1.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end

    spoke1.vm.provision "shell", inline: "ip route add 172.100.100.0/24 via 192.168.56.1"

    # Installing Microk8s
    spoke1.vm.provision "shell", inline: $microk8sTfsInstall

    spoke1.vm.provision "shell", inline: "echo Rebooting...", reboot: true
  end

end
