$linkerdReverseProxy = <<-'SCRIPT'
sudo apt update && sudo apt install nginx -y
echo 'server {
    listen 8084;

    location / {
        proxy_pass http://127.0.0.1:50750;
        proxy_set_header Host localhost;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}' > /home/vagrant/expose-linkerd									# NGINX reverse proxy configuration
sudo ln -s /home/vagrant/expose-linkerd /etc/nginx/sites-enabled/	# Create symlink of the NGINX configuration file
sudo systemctl restart nginx										# Commit the reverse proxy configurations
echo "linkerd viz dashboard &" >> .profile							# Enable start on login
SCRIPT

$microk8sTfsInstall = <<-'SCRIPT'
sudo dpkg --configure -a
sudo apt-get update -y
sudo apt --fix-broken install -y
sudo apt-get dist-upgrade -y
sudo apt-get install -y ca-certificates curl gnupg lsb-release snapd jq
sudo apt-get install -y docker.io docker-buildx
if [ -s /etc/docker/daemon.json ]; then sudo cat /etc/docker/daemon.json; else echo '{}'; fi \
    | jq 'if has("insecure-registries") then . else .+ {"insecure-registries": []} end' -- \
    | jq '."insecure-registries" |= (.+ ["localhost:32000"] | unique)' -- \
    | tee tmp.daemon.json
sudo mv tmp.daemon.json /etc/docker/daemon.json
sudo chown root:root /etc/docker/daemon.json
sudo chmod 600 /etc/docker/daemon.json
sudo systemctl restart docker
echo '192.168.56.2 controller' | sudo tee -a /etc/hosts
echo '192.168.56.3 spoke1' | sudo tee -a /etc/hosts
echo '192.168.56.4 spoke2' | sudo tee -a /etc/hosts
sudo snap install microk8s --classic --channel=1.24/stable
sudo snap alias microk8s.kubectl kubectl
sudo usermod -aG docker $USER
sudo usermod -aG microk8s $USER
sudo mkdir -p /home/$USER/.kube
sudo microk8s config > /home/$USER/.kube/config
sudo chown -f -R $USER /home/$USER/.kube
if [ "controller" == $(cat /etc/hostname) ]; then
    mkdir /home/$USER/tfs-ctrl
    git clone https://labs.etsi.org/rep/tfs/controller.git /home/$USER/tfs-ctrl
    chown -f -R $USER /home/$USER/tfs-ctrl
fi
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.define "controller" do |controller|
    controller.vm.box = "davidjosearaujo/teraflowsdncontroller"
    controller.vm.network "forwarded_port", guest: 80, host: 8080     # WebUI
    controller.vm.network "forwarded_port", guest: 8084, host: 50750  # Linkerd Viz Dashboard
    controller.vm.network "forwarded_port", guest: 8081, host: 8081   # CockroachDB Dashboard
    controller.vm.network "forwarded_port", guest: 8222, host: 8222   # NATS Dashboard
    controller.vm.network "forwarded_port", guest: 9000, host: 9000   # QuestDB Dashboard
    controller.vm.network "forwarded_port", guest: 9090, host: 9090   # Prometheus Dashboard

    controller.vm.hostname = "controller"
    controller.vm.network "private_network", ip: "192.168.56.2"

    controller.vm.provision "shell", inline: $linkerdReverseProxy

    controller.vm.provision "shell", inline: "ip route add 172.100.100.0/24 via 192.168.56.1"

    controller.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end

    # Update controller source code to the desired branch
    if ENV['BRANCH'] != nil
      controller.vm.provision "shell", inline: "cd ./tfs-ctrl && git pull && git switch " + ENV['BRANCH']
    end
  end

  config.vm.define "spoke1" do |spoke1|
    spoke1.vm.box = "ubuntu/focal64"

    spoke1.vm.hostname = "spoke1"
    spoke1.vm.network "private_network", ip: "192.168.56.3"

    spoke1.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end

    # Installing Microk8s
    spoke1.vm.provision "shell", inline: $microk8sTfsInstall
  end

  config.vm.define "spoke2" do |spoke2|
    spoke2.vm.box = "ubuntu/focal64"

    spoke2.vm.hostname = "spoke2"
    spoke2.vm.network "private_network", ip: "192.168.56.4"

    spoke2.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end

    # Installing Microk8s
    spoke2.vm.provision "shell", inline: $microk8sTfsInstall
  end

end
