Vagrant.configure("2") do |config|
  
  config.vm.define "controller" do |controller|
    controller.vm.box = "davidjosearaujo/teraflowsdncontroller"
    controller.vm.network "forwarded_port", guest: 80, host: 8080
    controller.vm.network "private_network", ip: "192.168.56.2"
  end

  config.vm.define "containerlab" do |containerlab|
    containerlab.vm.box = "davidjosearaujo/containerlab"
    containerlab.vm.network "private_network", ip: "192.168.56.3"
  end

end
