Vagrant.configure("2") do |config|
  
  config.vm.define "controller" do |controller|
    controller.vm.box = "davidjosearaujo/teraflowsdncontroller"
    controller.vm.network "forwarded_port", guest: 80, host: 8080     # WebUI
    controller.vm.network "forwarded_port", guest: 8084, host: 50750  # Linkerd Viz Dashboard
    controller.vm.network "forwarded_port", guest: 8081, host: 8081   # CockroachDB Dashboard
    controller.vm.network "forwarded_port", guest: 8222, host: 8222   # NATS Dashboard
    controller.vm.network "forwarded_port", guest: 9000, host: 9000   # QuestDB Dashboard
    controller.vm.network "forwarded_port", guest: 9090, host: 9090   # Prometheus Dashboard
    controller.vm.network "private_network", ip: "192.168.56.2"
    
    # Setup Linkerd Viz reverse proxy
    ## Copy config file
    controller.vm.provision "file" do |f|
      f.source = "./reverse-proxy-linkerdviz.sh"
      f.destination = "./reverse-proxy-linkerdviz.sh"
    end
    ## Execute configuration file
    controller.vm.provision "shell" do |s|
      s.inline = "chmod +x ./reverse-proxy-linkerdviz.sh && ./reverse-proxy-linkerdviz.sh"
    end

    # TESTING
    # Update controller source code to desired branch
    controller.vm.provision "shell" do |s|
      s.inline = "cd ./tfs-ctrl && git pull && git switch " + ENV['BRANCH']
    end

  end

  config.vm.define "containerlab" do |containerlab|
    containerlab.vm.box = "davidjosearaujo/containerlab"
    containerlab.vm.network "private_network", ip: "192.168.56.3"
  end

end