Vagrant.configure("2") do |config|
  
  config.vm.define "controller" do |controller|
    controller.vm.box = "davidjosearaujo/teraflowsdncontroller"
    controller.vm.network "forwarded_port", guest: 80, host: 8080     # WebUI
    controller.vm.network "forwarded_port", guest: 8084, host: 8084   # Linkerd Dashboard
    controller.vm.network "forwarded_port", guest: 8081, host: 8081   # CockroachDB Dashboard
    controller.vm.network "forwarded_port", guest: 8222, host: 8222   # NATS Dashboard
    controller.vm.network "forwarded_port", guest: 9000, host: 9000   # QuestDB Dashboard
    controller.vm.network "forwarded_port", guest: 9090, host: 9090   # Prometheus Dashboard
    controller.vm.network "private_network", ip: "192.168.56.2"
    
    controller.vm.provision "file" do |f|
      f.source = "./reverse-proxy-guis.sh"
      f.destination = "./reverse-proxy-guis.sh"
    end

    controller.vm.provision "shell" do |s|
      s.inline = "chmod +x ./reverse-proxy-guis.sh && ./reverse-proxy-guis.sh"
    end

  end

  config.vm.define "containerlab" do |containerlab|
    containerlab.vm.box = "davidjosearaujo/containerlab"
    containerlab.vm.network "private_network", ip: "192.168.56.3"
  end

end