Vagrant.configure("2") do |config|
  
  config.vm.define "hub" do |hub|
    hub.vm.box = "ubuntu/focal64"
    hub.vm.hostname = "hub"
    hub.vm.network "private_network", ip: "192.168.56.2"

    hub.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    
    hub.vm.provision "file" do |f|
      f.source = "./microk8s-install.sh"
      f.destination = "./microk8s-install.sh"
    end
    
    hub.vm.provision "shell" do |s|
      s.inline = "chmod +x ./microk8s-install.sh && ./microk8s-install.sh"
    end

  end

  config.vm.define "spoke1" do |spoke1|
    spoke1.vm.box = "ubuntu/focal64"
    spoke1.vm.hostname = "spoke1"
    spoke1.vm.network "private_network", ip: "192.168.56.3"

    spoke1.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    spoke1.vm.provision "file" do |f|
      f.source = "./microk8s-install.sh"
      f.destination = "./microk8s-install.sh"
    end
    
    spoke1.vm.provision "shell" do |s|
      s.inline = "chmod +x ./microk8s-install.sh && ./microk8s-install.sh"
    end
  end

  config.vm.define "spoke2" do |spoke2|
    spoke2.vm.box = "ubuntu/focal64"
    spoke2.vm.hostname = "spoke2"
    spoke2.vm.network "private_network", ip: "192.168.56.4"

    spoke2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    spoke2.vm.provision "file" do |f|
      f.source = "./microk8s-install.sh"
      f.destination = "./microk8s-install.sh"
    end
    
    spoke2.vm.provision "shell" do |s|
      s.inline = "chmod +x ./microk8s-install.sh && ./microk8s-install.sh"
    end
  end

end
