$linkerdReverseProxy = <<-'SCRIPT'
sudo apt update && sudo apt install nginx -y
echo 'server {
    listen 8084;

    location / {
        proxy_pass http://127.0.0.1:50750;
        proxy_set_header Host localhost;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}' > /home/vagrant/expose-linkerd									                # NGINX reverse proxy configuration
sudo ln -s /home/vagrant/expose-linkerd /etc/nginx/sites-enabled/	# Create symlink of the NGINX configuration file
sudo systemctl restart nginx										                  # Commit the reverse proxy configurations
echo "linkerd viz dashboard &" >> .profile							          # Enable start on login
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.define "controller" do |controller|
    controller.vm.box = "davidjosearaujo/teraflowsdncontroller"
    controller.vm.network "forwarded_port", guest: 80, host: 8080     # WebUI
    controller.vm.network "forwarded_port", guest: 8084, host: 50750  # Linkerd Viz Dashboard
    controller.vm.network "forwarded_port", guest: 8081, host: 8081   # CockroachDB Dashboard
    controller.vm.network "forwarded_port", guest: 8222, host: 8222   # NATS Dashboard
    controller.vm.network "forwarded_port", guest: 9000, host: 9000   # QuestDB Dashboard
    controller.vm.network "forwarded_port", guest: 9090, host: 9090   # Prometheus Dashboard
    controller.vm.network "private_network", ip: "192.168.56.2"

    controller.vm.provision "shell", inline: $linkerdReverseProxy

    controller.vm.provision "shell", inline: "ip route add 172.100.100.0/24 via 192.168.56.1"

    controller.vm.provider "virtualbox" do |v|
      v.memory = 6144
      v.cpus = 4
    end

    # Update controller source code to the desired branch
    if ENV['BRANCH'] != nil
      controller.vm.provision "shell", inline: "cd ./tfs-ctrl && git pull && git switch " + ENV['BRANCH']
    end
  end
end
