Vagrant.configure("2") do |config|

  config.vm.define "controller" do |controller|
    controller.vm.box = "davidjosearaujo/teraflowsdncontroller"
    controller.vm.network "private_network", ip: "192.168.56.2"

    controller.vm.provision "shell", inline: "ip route add 172.100.100.0/24 via 192.168.56.1"

    controller.vm.provider "virtualbox" do |v|
      v.memory = 8192
      v.cpus = 4
    end

    # Update controller source code to the desired branch
    if ENV['BRANCH'] != nil
      controller.vm.provision "shell", inline: "cd ./tfs-ctrl && git pull && git switch " + ENV['BRANCH']
    end
  end
end
